name: OWASP ZAP Full Scan CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: DAST: OWASP ZAP Full Scan

    env:
      # opcional: si tu app requiere autenticación HTTP
      ZAP_AUTH_HEADER: ${{ secrets.ZAP_AUTH_HEADER }}
      ZAP_AUTH_HEADER_VALUE: ${{ secrets.ZAP_AUTH_HEADER_VALUE }}
      ZAP_AUTH_HEADER_SITE: ${{ secrets.ZAP_AUTH_HEADER_SITE }}

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Run OWASP ZAP Full Scan'
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}          # necesario para crear issues automáticamente
        target: ${{ secrets.ZAP_TARGET_URL }}       # agregar este secret con la URL de tu app
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        rules_file_name: '.zap/rules.tsv'           # opcional: lista de alertas a ignorar
        cmd_options: '-a -j -z "-config view.locale=en_US"' 
          # -a: activa reglas alfa,
          # -j: usa Ajax spider:contentReference[oaicite:1]{index=1}.
        fail_action: 'true'                         # hacer que el pipeline falle si hay alertas
        artifact_name: 'zap_full_scan_report'

    - name: 'Upload ZAP report'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: 'zap_scan_results'
        path: |
          zap_scan.html
          zap_scan.md
          zap_report.json

    - name: 'Post summary to PR'
      if: success() && github.event_name == 'pull_request'
      run: |
        echo "ZAP scan passed with no FAILs 🎉" || true
